server:
  port: 8088
spring:
  datasource:

    url: jdbc:mysql://localhost:3306/shophandmade
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
#      url: jdbc:mysql://viaduct.proxy.rlwy.net:58827/shophandmade
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      username: root
#      password: g4BgHHC4BfBd3B4-1AGE42GGdhdb6Gg1
  #jPa la viet tat cua Java Persitence API dung de lam viec voi csl,dung cac method ham thay vi cau lenh thuan
  jpa:
    #hien cac cau lenh sql
    show-sql: true
    hibernate:
      #Cac cau lenh tu dong khong duoc thao tac ma thao tac bang sql
      ddl-auto: none
    properties:
      hibernate:
      #Driver ket noi voi CSDL
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true

##tao tai khoan sa,vo sql congig chon network bat tcp len
#spring:
#  datasource:
#    url: jdbc:sqlserver://localhost:1433;databaseName=shophandmade;encrypt=false;trustServerCertificate=false
#
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    username: sa
#    password: 123456
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.SQLServerDialect
#        format_sql: true

#gioi han kich thuoc chuyen du lieu
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#bien tro duong dan
api:
  prefix: api/v1
jwt:
  expiration: 604800 #7 days = 7 * 24 * 60 * 60
  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=
messages:
   basename: i18n/messages
   encoding: UTF-8
   default-locale: en


